#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 24 15:39:31 2021

@author: mandel94
"""

'''This module contains the main program for creating our NBA database.
   This are the steps to be taken:
       - define the schema of the database;
       - initialize the database;
       - populate the database in a programmatic and progressive fashion, by 
             means of using the toolkit we built up in the previous stages of 
             the project.
'''